version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: resume_api
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

volumes:
  progresDB:
